export class PharmacyConstants {

    public static LIST_OF_TYPE_OF_PHARMACY: Array<string> = [
        "AMPOULE",
        "CAPLET",
        "CAPSULE",
        "CREAM",
        "DENTAL CONES",
        "DOUCHES",
        "DROPS",
        "ELIXIR",
        "EMULSION",
        "GARGLES",
        "GEL",
        "GRANULES",
        "INFUSION PUMP",

        "INHALER",
        "INJECTION",
        "IUD",
        "KIT",
        "LINCTUSES",
        "LINIMENT",


        "LIQUID",
        "LOTION",
        "LOZENGE",
        "MAGMAS",
        "MOUTH WASHES",
        "NEBULIZER/ATOMIZER",

        "OINTMENT",
        "PAINTS",
        "PASTE",
        "PASTILLES",
        "PATCH",
        "PELLETS",

        "PELLETS",
        "PESSARY",
        "PILLS",
        "PLASTERS",
        "POULTICE",
        "POWDER",

        "SHAMPOO",
        "SOAP",
        "SOLUTION",
        "SPRAY",
        "STRIP",
        "SUPPOSITORY",
        "SUSPENSION",

        "SWAB",
        "SYRUP",
        "TABLET",
        "TINCTURES",
        "TROCHE",
    ];

    public static UNITS_OF_PHARMACY = [
        "Drops",
        "ml",
        "Puffs",
        "Number",
        "As Applicable"
    ]

    public static FREQUENCY_OF_PHARMACY = [
        { value: "1", display: "Daily" },
        { value: "2", display: "Alternate Days" },
        { value: "7", display: "Once in a week" },
        { value: "14", display: "Once in 2 weeks" },
        { value: "30", display: "Once in a month" },
        { value: "60", display: "Once in 2 months" },
        { value: "90", display: "Once in 3 months" },
        { value: "3", display: "Once in 3 days" },
        { value: "4", display: "Once in 4 days" },
        { value: "5", display: "Once in 5 days" },
        { value: "6", display: "Once in 6 days" },
        { value: "8", display: "Once in 8 days" },
        { value: "9", display: "Once in 9 days" },
        { value: "10", display: "Once in 10 days" },
        { value: "11", display: "Once in 11 days" },
        { value: "12", display: "Once in 12 days" },
        { value: "13", display: "Once in 13 days" },
        { value: "15", display: "Once in 15 days" },
        { value: "16", display: "Once in 16 days" },
        { value: "17", display: "Once in 17 days" },
        { value: "18", display: "Once in 18 days" },
        { value: "19", display: "Once in 19 days" },
        { value: "20", display: "Once in 20 days" },
        { value: "21", display: "Once in 21 days" },
        { value: "22", display: "Once in 22 days" },
        { value: "23", display: "Once in 23 days" },
        { value: "24", display: "Once in 24 days" },
        { value: "25", display: "Once in 25 days" },
        { value: "26", display: "Once in 26 days" },
        { value: "27", display: "Once in 27 days" },
        { value: "28", display: "Once in 28 days" },
        { value: "29", display: "Once in 29 days" },
        { value: "31", display: "Once in 31 days" },
        { value: "32", display: "Once in 32 days" },
        { value: "33", display: "Once in 33 days" },
        { value: "34", display: "Once in 34 days" },
        { value: "35", display: "Once in 35 days" },
        { value: "36", display: "Once in 36 days" },
        { value: "37", display: "Once in 37 days" },
        { value: "38", display: "Once in 38 days" },
        { value: "39", display: "Once in 39 days" },
        { value: "40", display: "Once in 40 days" },
        { value: "41", display: "Once in 41 days" },
        { value: "42", display: "Once in 42 days" },
        { value: "43", display: "Once in 43 days" },
        { value: "44", display: "Once in 44 days" },
        { value: "45", display: "Once in 45 days" },
        { value: "46", display: "Once in 46 days" },
        { value: "47", display: "Once in 47 days" },
        { value: "48", display: "Once in 48 days" },
        { value: "49", display: "Once in 49 days" },
        { value: "50", display: "Once in 50 days" },
        { value: "51", display: "Once in 51 days" },
        { value: "52", display: "Once in 52 days" },
        { value: "53", display: "Once in 53 days" },
        { value: "54", display: "Once in 54 days" },
        { value: "55", display: "Once in 55 days" },
        { value: "56", display: "Once in 56 days" },
        { value: "57", display: "Once in 57 days" },
        { value: "58", display: "Once in 58 days" },
        { value: "59", display: "Once in 59 days" },
    ];

    public static DURATION_OF_PHARMACY = [
        { value: "1", display: "1 Day" },
        { value: "2", display: "2 Days" },
        { value: "3", display: "3 Days" },
        { value: "5", display: "5 Days" },
        { value: "7", display: "7 Days" },
        { value: "10", display: "10 Days" },
        { value: "14", display: "2 Weeks" },
        { value: "21", display: "3 Weeks" },
        { value: "30", display: "1 Month" },
        { value: "60", display: "2 Months" },
        { value: "90", display: "3 Months" },
        { value: "120", display: "4 Month" },
        { value: "180", display: "6 Months" },
        { value: "365", display: "1 Year" },
    ];

    public static MEAL_INTAKE = [
        "Before Meals",
        "After Meals",
        "Not Applicable"
    ];

    public static INTAKE_ROUTE = [
        "Ophthalmic",
        "Buccal",
        "Topical",
        "Oral",
        "Ear",
        "Nasal",
        "Sublingual",
        "IM",
        "IV",
        "SC",
        "IDir",
    ];

    public static INTAKE_TIME = [
        { value: "1800000", display: "06:00 AM" },
        { value: "3600000", display: "06:30 AM" },
        { value: "5400000", display: "07:00 AM" },
        { value: "7200000", display: "07:30 AM" },
        { value: "9000000", display: "08:00 AM" },
        { value: "10800000", display: "08:30 AM" },
        { value: "12600000", display: "09:00 AM" },
        { value: "14400000", display: "09:30 AM" },
        { value: "16200000", display: "10:00 AM" },
        { value: "18000000", display: "10:30 AM" },
        { value: "19800000", display: "11:00 AM" },
        { value: "21600000", display: "11:30 AM" },
        { value: "23400000", display: "12:00 PM" },
        { value: "25200000", display: "12:30 PM" },
        { value: "27000000", display: "01:00 PM" },
        { value: "28800000", display: "01:30 PM" },
        { value: "30600000", display: "02:00 PM" },
        { value: "32400000", display: "02:30 PM" },
        { value: "34200000", display: "03:00 PM" },
        { value: "36000000", display: "03:30 PM" },
        { value: "37800000", display: "04:00 PM" },
        { value: "39600000", display: "04:30 PM" },
        { value: "41400000", display: "05:00 PM" },
        { value: "43200000", display: "05:30 PM" },
        { value: "45000000", display: "06:00 PM" },
        { value: "46800000", display: "06:30 PM" },
        { value: "48600000", display: "07:00 PM" },
        { value: "50400000", display: "07:30 PM" },
        { value: "52200000", display: "08:00 PM" },
        { value: "54000000", display: "08:30 PM" },
        { value: "55800000", display: "09:00 PM" },
    ]

    public static DOSAGES = [
        { value: "0-0-0-1", display: "0 - 0 - 0 - 1" },
        { value: "0-1-0-0", display: "0 - 1 - 0 - 0" },
        { value: "1-0-0-1", display: "1 - 0 - 0 - 1" },
        { value: "1-0-1-0", display: "1 - 0 - 1 - 0" },
        { value: "0-1-1-0", display: "0 - 1 - 1 - 0" },
        { value: "1-1-1-0", display: "1 - 1 - 1 - 0" },
        { value: "1-1-0-1", display: "1 - 1 - 0 - 1" },
        { value: "1-1-1-1", display: "1 - 1 - 1 - 1" },
        { value: "0-0-1-0", display: "0 - 0 - 1 - 0" },
        { value: "1-0-0-0", display: "1 - 0 - 0 - 0" },
        { value: "0-1-0-1", display: "0 - 1 - 0 - 1" },
        { value: "1-1-0-0", display: "1 - 1 - 0 - 0" },
        { value: "0-0-1-1", display: "0 - 0 - 1 - 1" },
        { value: "0-1-1-1", display: "0 - 1 - 1 - 1" },
        { value: "1-0-1-1", display: "1 - 0 - 1 - 1" }
    ]
}