export enum DiscountType {
    TYPE_CONSULTATION_DISCOUNT = 1,
    TYPE_PHARMACY_DISCOUNT = 2,
    TYPE_DIAGNOSTIC_DISCOUNT = 3,
    TYPE_WELLNESS_DISCOUNT = 4,
    TYPE_IMMUNIZATION = 5,
    TYPE_PROCEDURE = 6,
    TYPE_PACKAGE = 7,
    TYPE_MISCELLANEOUS = 8
}